#!/bin/bash

function blat {
  echo "
  now          $now
  check_file   $check_file
  file_time    $file_time
  warning_time $warning_time
  time_diff    $time_diff
  "
}

warning_time=$(echo '60*60*24*50' | bc)
#warning_time=234
now=$(date +%s)
check_file=/home/oki/.rea-auth/amuhrer.cer
file_time=$(ls -l --time-style=+%s $check_file|awk '{print $6}')
time_diff=$(( now - file_time ))


if [[ $time_diff -gt $warning_time ]]; then
  exit 1
else
  exit 0
fi

