#!/bin/bash

set -euo pipefail

while read line; do
  if [[ $(echo $line | grep '^ *##') ]] ; then  # two hashes to ignore top-level headings
    echo $line |sed -E 's/^ *#/ /; s/#/  /g; s/( *)(.*)$/\1* [\2]\L(#\2)/; :a ; s/(.*\(#[-a-z0-9]+) /\1-/; ta'
  fi

done < /dev/stdin
