#!/bin/bash
# shellcheck disable=SC2086,SC2046
# no spaces in _my_ filenames

set -euo pipefail

# does a quick thumbnail in $PWD to check position
source $HOME/scan-defaultrc

name=position-test
resolution=100

rm ${name}*
scanimage --device "$device" --format=png --buffer-size=128 --resolution=$resolution  > $name.png

echo convert ${name}.png  -virtual-pixel edge -blur $blur -fuzz $fuzz% -trim -format '%wx%h%O' info:

magick $name.png -crop $(magick ${name}.png  -virtual-pixel edge -blur $blur -fuzz $fuzz% -trim -format '%wx%h%O' info:) $name-trimmed.png

