#!/bin/bash
# shellcheck disable=SC2086,SC2012,SC2046
set -euo pipefail
source $HOME/scan-defaultrc

input_name=${1:?ERROR need a name}
name=$input_name

src=$trimmed/$name
dest=$sized/$name

if [[ ! -d $src ]] ; then
  echo ERROR: $src does not exist
  exit 1
fi

if [[ -d $dest ]] ; then
  echo ERROR: $dest already exists
  exit 1
fi

mkdir -p $dest

for source_file in $(ls $src/*[^%].png|sort) ; do
  # we are not processing anything that matches `%.png` - we dont want to resize our resizes
  echo source: $source_file
  filename=$(basename $source_file)
  clean_filename=${filename/\.png/}

  for size in 5 10 20 50; do
    dest_file="$dest/${clean_filename}_${size}%.png"
    echo destination: $dest_file
    time magick $source_file -resize $size% +repage $dest_file
  done
done
exit

